# Generated by Django 3.2.3 on 2021-05-13 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('form', models.CharField(choices=[('A', 'ATX'), ('M', 'MicroATX')], default='A', max_length=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('link', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Chipset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('A', 'AMD'), ('I', 'Intel')], default='A', max_length=1)),
                ('chip_model', models.CharField(max_length=100)),
                ('cores', models.IntegerField()),
                ('threads', models.IntegerField()),
                ('speed', models.DecimalField(decimal_places=2, max_digits=3)),
                ('tdp', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('link', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Graphics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('A', 'AMD'), ('N', 'NVIDIA')], default='A', max_length=1)),
                ('graphics_model', models.CharField(max_length=100)),
                ('ram', models.IntegerField()),
                ('tdp', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('link', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MotherBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('form', models.CharField(choices=[('A', 'ATX'), ('M', 'MicroATX')], default='A', max_length=1)),
                ('socket', models.CharField(choices=[('A', 'AMD'), ('I', 'Intel')], default='A', max_length=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('link', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='OS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('0', 'No OS'), ('w', 'Windows'), ('l', 'Linux')], default='0', max_length=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('link', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PSU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cert', models.CharField(choices=[('0', 'None'), ('b', '80 Plus Bronze'), ('s', '80 Plus Silver'), ('g', '80 Plus Gold'), ('p', '80 Plus Platinum'), ('t', '80 Plus Titanium')], default='0', max_length=1)),
                ('wattage', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('link', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Ram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('speed', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('link', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CustomComputer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='main_app.case')),
                ('cpu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='main_app.chipset')),
                ('gpu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='main_app.graphics')),
                ('mobo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='main_app.motherboard')),
                ('os', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='main_app.os')),
                ('psu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='main_app.psu')),
                ('ram', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='main_app.ram')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
