# Generated by Django 3.2.3 on 2021-05-13 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_graphics_ramtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphics',
            name='ramType',
            field=models.CharField(choices=[('4', 'GDDR4'), ('5', 'GDDR5'), ('6', 'GDDR6')], default='4', max_length=1),
        ),
    ]
